### ISSUE TITLE
Cant use it properly without "spgithub"

### ISSUE THREAD

**Issue by Ysejal** [KyleLavorato/gitclean-jenkins#1]
Hello, where I can found "spgithub.groovy" to use this tool ?

**Comment by KyleLavorato** [comment]
Those functions were provided in the `SupportingFunctions.groovy` file, and were originally intended to be imported to the main code via a shared library. To make things easier I have combined it all into the `git-cleanup.groovy` script in this [commit](https://github.com/KyleLavorato/gitclean-jenkins/commit/6f51084069a8ee84cd9c717ff0c1a8a9466989ed).

You should have no issues now with missing functions.

**Comment by Ysejal** [comment]
Okay, thank you for the information
